# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lan for Android Firebase app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor prod --target lib/main_prod.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: ENV["ANDROID_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-prod-release.apk",
      testers: "ahmed.bauiomy17@gmail.com, m_ellisy@hotmail.com",
      release_notes: "New release with bug fixes and performance improvements."
  )
  end
end
